title: Devs at ELPSA.org
title_footer: ELPSA.org
email: info@elpsa.org
description: Proyek GPFD (Government Partnership for Development) oleh [University of Canberra](http://www.canberra.edu.au) bekerjasama dengan [IKIP Mataram](http://ikipmataram.ac.id), [LPMP NTB](http://lpmpntb.org), [DIKPORA NTB](http://dikpora.ntbprov.go.id), dan [KEMENAG NTB](https://ntb.kemenag.go.id) dan didukung oleh [DFAT Australia](http://dfat.gov.au) dan [Australian Aid](https://australianaid.org).
author: UC - IKIP Mataram